### ISSUE TITLE
API Gateway inconsistencies

### ISSUE THREAD

**Issue by rogueturnip** [localstack/serverless-localstack#109]
So I'm working with the latest docker image for localstack and latest npm for serverless-localstack and I've noticed three issues with the API Gateway implementation that impact the ability to use it for local testing.

1. Header parameter casing is changed.  What I mean by this is if you send in something like X-USERID localstack converts this to X-Userid.  In AWS it retains the casing
1. Overlapping http paths are not predictable.  I have 2 paths, /photos/{photoId} and /photos/upload.  In AWS if I send in /photos/upload it will use the right one, with localstack it will sometimes use /photos/{photoId} for this and pass in "upload" s the photoId.
1. s3 handler events do not get added to the s3 bucket.  I created a lambda handler for s3:ObjectCreated:* and then used the cli to check if it was attached and it was not there.  I could add this manually and it works as expected but the event in serverless.yml should also add it.

Thanks for the great work with this.  It really moves closer to doing some solid testing before production deployment.

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-26) by [Unito](https://www.unito.io/learn-more)

**Comment by steffyP** [comment]
Hi @rogueturnip, 

apologies for the late reply. We did a lot of improvements in the API gateway implementation, and also for S3 in the meantime. Could you please upgrade to the `latest` version of localstack and `serverless-localstack` and let us know if you still encounter any issues. 
If you do so, it would very helpful if you could provide your `serverless.yml` configuration and the logs from localstack.

**Comment by steffyP** [comment]
This issue seems to be stale. As we didn't get any response in two months, and the original report is from 2020, we are closing this issue now. Please feel free to reopen if it still persists, and provide updates logs and details.
