### ISSUE TITLE
Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by joarleymoraes** [localstack/serverless-localstack#12]
Getting the following error when using `sls deploy --stage local`:

```
Serverless Error ---------------------------------------

  Serverless plugin "serverless-localstack" initialization errored: Cannot read property 'bind' of undefined

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           11.0.0
     Serverless Version:     1.32.0
```

I have used `SLS_DEBUG` and found the error is coming from:

`TypeError: Cannot read property 'bind' of undefined
    at LocalstackPlugin.skipIfMountLambda 
(/.../node_modules/serverless-localstack/src/index.js:102:51)`

**Comment by RocketPuppy** [comment]
@joarleymoraes Looks like the method that's trying to be referenced was only added in serverless 1.38.0. Upgrading fixed the issue for me, you might want to see if it works for you.

Code referencing the method: https://github.com/localstack/serverless-localstack/blob/master/src/index.js#L81
Commit adding the method: https://github.com/serverless/serverless/commit/2ad01b3fe362ba296bfd9ddbb6405abb3bb1e8ab
