### ISSUE TITLE
Recoverable error occurred (socket hang up), sleeping for 5 seconds. Try 4 of 4

### ISSUE THREAD

**Issue by ravithejappl** [localstack/serverless-localstack#127]
I am getting socket hangup error, is it because of all aws apis are running 4566? I am running localstack image created from [localstack](https://github.com/localstack/localstack) not from this repo docker-compose file.

**Comment by ichinna** [comment]
@ravithejappl  
did you figure this out?

**Comment by steffyP** [comment]
Closing the ticket due to inactivity, assuming the issue has been resolved in the meantime.
