### ISSUE TITLE
Lambda execution does not work with package individually: true

### ISSUE THREAD

**Issue by maturiaditya** [localstack/serverless-localstack#141]
Lambda execution does not work with package (individually: true). Each lambda is created with it's own folder and when I execute a lambda using localstack url, it fails with  "errorMessage" : "Error: Cannot find module ....". I am not sure if I am missing any config here.

**Comment by ThomasLabstep** [comment]
> Cannot find module

Show us the full log. It could just be the same error I got.
My solution was simply to npm update and use the latest webpack 5.
Check what your packaged zip look like.

**Comment by steffyP** [comment]
Closing the ticket due to inactivity and a proposed solution. Please reach out if you still encounter issues and provide more details, and logs.
