### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by vincentpham13** [localstack/serverless-localstack#150]
![image](https://user-images.githubusercontent.com/63580042/121021245-5f887900-c7cb-11eb-8e8d-71864d3a8ad7.png)

**Comment by whummer** [comment]
Thanks for reporting @vincentpham13 . This seems like an issue related to data persistence - can you please try again after removing the `DATA_DIR` configuration (or setting `DATA_DIR=`). Please keep us posted how it goes.. Thanks!

**Comment by steffyP** [comment]
Closing the ticket do to inactivity. Please reach out if you still encounter any issues.
