### ISSUE TITLE
Turning off mount code results in no lambda function resource

### ISSUE THREAD

**Issue by luke-grassroot** [localstack/serverless-localstack#17]
This is clearly related to issue #5, which fixed the problem for non-local stages. The issue is that if mount code is turned off, the cloud formation update template is missing the actual lambda function resource. Working off of the super helpful notes that @lwoodson on #5, I managed to isolate this as the behaviour within the skipIfMountLambda method in index.js.

What happens is, so far as I can tell, that if mount code is false, on line 80 in index.js this is hit:

`this.skipIfMountLambda('AwsCompileFunctions', 'compileFunction', compileFunction);`

The presence of compileFunction then means that instead of line 119 being hit if mount code is false, and the original function just returned, instead it's just lines 55-57, i.e., this is triggered:

```
if (!this.shouldMountCode()) { 
   return Promise.resolve(); 
}
````

I.e., instead of the original AWS compile happening, an empty promise is returned.

It seems to me the simple solution is to insert a check for whether mountcode is on to the beginning of skipIfMountLambda, i.e., something like this, inserted at line 106:

```
if (!this.shouldMountCode()) {
      this.log('Not skipping plugin function ' + functionName + ' (lambda.mountCode not enabled)');
      return;
}
```

This also seems to me much cleaner. If mount code is off then there's no point bothering with all the rest of the logic in that block and should just do nothing (ie skip if mount lambda, do nothing otherwise). I have tested and inserting those lines solves the problem. **But** I admit that I haven't fully digested everything happening in this sequence, so am not sure if that might not introduce side effects - although the tests pass, as does running it on a couple of my lambdas.

If this seems like the right way to go I'm happy to do a PR. Otherwise, what's the best way to fix?

**Comment by sbv-trueenergy** [comment]
Seeing the same thing here

**Comment by whummer** [comment]
Thanks for reporting @luke-grassroot @sbv-trueenergy . Can you please try again with the latest version - released as npm version `0.4.12`

**Comment by sbv-trueenergy** [comment]
Seems to work now. I got an unrelated error on the autostart docker thing  I'll see if it happens again before reporting a new issue:
```
Serverless: Starting LocalStack in Docker. This can take a while.
 
  Range Error [ E R R_ C H I L D_ P R O C E S S_ S T D I O_ M A X B U F F E R] 
 
  stdout maxBuffer length exceeded
```

**Comment by whummer** [comment]
Thanks for confirming. Closing this issue now - please re-open if the problem persists.

@sbv-trueenergy Can you please open a separate ticket for the new error, with instructions how to reproduce the issue? Thanks
