### ISSUE TITLE
Serverless 3.0 Support

### ISSUE THREAD

**Issue by brucekaufman** [localstack/serverless-localstack#179]
It seems that this plugin does not presently support serverless 3.0.  I tried updating one of our internal projects to use serverless 3.0 and deployment to localstack is failing:

```
Deploying communication-infrastructure to stage local (us-east-1)

Uploading CloudFormation file to S3
Skipping template validation: Unsupported in Localstack
Creating new change set

× Stack communication-infrastructure-local failed to deploy (0s)
Environment: linux, node 14.19.0, framework 3.2.0 (local), plugin 6.0.0, SDK 4.3.1
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Specify exactly one of 'TemplateBody' or 'TemplateUrl'
```

**Comment by whummer** [comment]
Hi @brucekaufman , thanks for reporting. Just to confirm, have you been able to run the plugin with Serverless 3.0 in the meantime? Thanks

**Comment by brucekaufman** [comment]
@whummer yes, I was able to get it working, i am running an outdated version of localstack because bugs in the newer releases are preventing an update, but the newer version does not show this error.
