### ISSUE TITLE
Specific endpoint url  format or development id or random id 

### ISSUE THREAD

**Issue by jktan0504** [localstack/serverless-localstack#189]
Hi dear devs, would like to know how can I specific the url format or define my own development random id inside the url ?

`
endpoint: http://localhost:4566/restapis/hjq33nkd9f/local/_user_request_
functions:
  hello: api-local-hello (17 MB)
  world: api-local-world (17 MB)
`

I would like to know or set "hjq33nkd9f" for my other local machine or app to connect the API.

Thanks

**Comment by drauedo** [comment]
Howdy,

To change the random ID, i.e, of the endpoint in Localstack you need to use the [flag](https://docs.localstack.cloud/user-guide/aws/apigateway/#custom-ids-for-api-gateway-resources-via-tags)  `–tags='{"_custom_id_":"myid123"}` when creating the Api, like this:
`awslocal apigateway create-rest-api --name my-api --tags '{"_custom_id_":"myid123"}'`

I tried to find a similar configuration to set that flag in the Serverless’ YAML configuration, but I wasn’t successful.

As a possible workaround, I would suggest creating the API in Localstack by following the steps on the docs and then [referencing](https://www.serverless.com/framework/docs/providers/aws/events/apigateway#share-api-gateway-and-api-resources) it in the Serverless Yaml by using the following lines:
```
provider:
  restApiId: XXXXX 
  restApiRootResourceId: XXXXX

```
This values can be listed by running the following command `awslocal apigateway get-rest-apis`. This will print an output similar to this: 
```
{
    "items": [
        {
            "id": "myid123",
            "name": "API Gateway Lambda integration",
            "createdDate": 1720884745.0,
            "apiKeySource": "HEADER",
            "endpointConfiguration": {
                "types": [
                    "EDGE"
                ]
            },
            "tags": {
                "_custom_id_": "myid123"
            },
            "disableExecuteApiEndpoint": false,
            "rootResourceId": "XXXXX"
        }
}
```
