### ISSUE TITLE
Deployment get stuck when add an authorizer

### ISSUE THREAD

**Issue by JoaquinDPC** [localstack/serverless-localstack#199]
Hello! I'm new in serverless and localstack. I was trying to implement integration tests using HTTP requests. And everything is working properly, the problem comes in when I add a custom authorizer to my functions, the deployment get stuck without getting any error. 

serverless version 2.72.3
serverless localstack version 0.4.36
serverless esbuild version 1.27.0

This is my serverless.yml
```
service: localstack

variablesResolutionMode: 20210326

custom:
  localstack:
    stages:
      - local
    host: http://localstack
    lambda:
      mountCode: false
    autostart: false
    debug: true
  servicesEndpoint: http://localstack:4566
  esbuild:
    bundle: true
    target: node14
    minify: false
    sourcemap: true
    keepNames: true
    plugins: ./esbuild-localstack-plugins.js
  environment: local

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  region: us-east-1
  stage: local
  timeout: 30
  versionFunctions: false
  eventBridge:
    useCloudFormation: true
  environment: ${file(./integration-tests/docker/localstack-variables.js)}

package:
  individually: true

plugins:
  - serverless-esbuild
  - serverless-localstack
  - serverless-stack-output

functions:
  create-user:
    handler: src/create-user.handler
    events:
      - http:
          method: post
          path: merchant
          authorizer: local-authorizer
  local-authorizer:
    handler: src/local-authorizer.handler
    events:
      - http:
          method: get
          path: merchants


resources:
  Outputs:
    ServiceEndpoint:
      Description: the custom service endpoint
      Value: ${self:custom.servicesEndpoint}
```

Run command:
`SLS_DEBUG=* docker-compose $OPTIONS run entities-app npx serverless --config serverless.localstack.yml deploy --verbose --stage local`

Result
![image (2)](https://user-images.githubusercontent.com/65637962/203091909-8bf0b4f2-0f9a-47ee-97bb-059c10583cc4.png)

**Comment by whummer** [comment]
Thanks for reporting @JoaquinDPC . Just to confirm - are you using the Community or the Pro version of LocalStack? Please note that certain features (including API Gateway authorizers) require a Pro API key - you can sign up for a free trial under https://app.localstack.cloud

Would be great if you could also share the logs of your LocalStack Docker container (with `DEBUG=1` enabled) - this would be super helpful in debugging this issue.. Thanks!

**Comment by steffyP** [comment]
Hi @JoaquinDPC, 

following up on our last message: could you please provide the requested information?

**Comment by steffyP** [comment]
This issue seems to be stale. As we didn't get any response in two months, we are closing this issue now. Please feel free to reopen if it still persists, and provide updates logs and details.
