### ISSUE TITLE
Remove references to the AWS SDK v2

### ISSUE THREAD

**Issue by mridang** [localstack/serverless-localstack#225]
As the AWS SDK v2 is being deprecated (and is currently in maintenance mode), we should. change this library to use the AWS SDK v3.

https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html

**Comment by nireld** [comment]
+1

**Comment by pinzon** [comment]
Thank you for bringing this issue to our attention. After thorough investigation, we've decided to postpone the migration to AWS SDK v3. This delay is attributed to the plugin's complete dependency on the version employed by the Serverless CLI. Once the Serverless CLI undergoes its migration, we will initiate our efforts to transition accordingly.

If you find the warning disruptive, you may consider exploring a potential solution available in the Serverless repository: [link to the solution](https://github.com/serverless/serverless/discussions/11750). We appreciate your understanding and patience as we work through this process.
