### ISSUE TITLE
serverless deploy --stage local returning an error - Inaccessible host: `127.0.0.1' at port `4566'.

### ISSUE THREAD

**Issue by enochadane** [localstack/serverless-localstack#226]
Inaccessible host: `127.0.0.1' at port `4566'. This service may not be available in the `us-east-1' region.

**Comment by steffyP** [comment]
Hi @enochadane,

thanks for your report. Could you please provide some more details? E.g. when do you see this error? 
Could you describe how you start localstack, and share your `serverless.yml`.

**Comment by steffyP** [comment]
This issue seems to be stale. As we didn't get any response in two months, we are closing this issue now. Please feel free to reopen if it still persists, and provide updates logs and details.
