### ISSUE TITLE
Problem with AppSync pipeline functions when there is more than 50 of them

### ISSUE THREAD

**Issue by darbinyanbabken** [localstack/serverless-localstack#227]
I have a setup of Serverless + AppSync + Localstack.
When in the project there is more than 50 AppSync Pipeline Functions all of them created after 50th are not available/visible for my  Serverless. Even if I can see Pipeline Functions successfully created with AWS CLI, I can not use them in my resolvers when deploying to local. Deployment fails with "undefined" error message.

**Comment by steffyP** [comment]
Hi @darbinyanbabken,

thanks for your issue report. 
Could you please provide a code snippet, so that we can reproduce your issue?

**Comment by steffyP** [comment]
Hi @darbinyanbabken, 

if this is still a pressing issue, we would kindly ask to provide a code snippet, or sample so we are able to reproduce your issue.

**Comment by steffyP** [comment]
Hi @darbinyanbabken, 
we never heard back from you and would need a code snippet for reproduction. 
If you still encounter the issue, please reopen the ticket. We are closing it now due to inactivity.
