### ISSUE TITLE
Attach IDE debugger

### ISSUE THREAD

**Issue by throrin19** [localstack/serverless-localstack#232]
Hello, 

I just ask if it's possible to attach vscode debugger to deployed lambdas over serverless-localstack

**Comment by joe4dev** [comment]
Hi @throrin19 

Yes, that is possible. Please check out our [Remote Debugging](https://docs.localstack.cloud/user-guide/tools/lambda-tools/debugging/) documentation. The setup depends a bit on the language and build process.
🚧 Notice that with VSCode, there is currently a limitation that debugging only works for one Lambda

We are looking forward to hearing your feedback 👂 Feel free to share your thoughts on how we can improve the debugging experience with LocalStack 📈
