### ISSUE TITLE
Localstack deployment fails

### ISSUE THREAD

**Issue by MarioSimou** [localstack/serverless-localstack#233]
When I deploy my code in a locastack container, the cloudformation deployment fails and I am not sure why. Initially I thought is a bundler issue, so I tested it with `webpack` and `esbuild`, but unfortunately the issue persists in both of them. I have also tested the issue with different versions of localstack(v1.4, v2.2). In all cases the deployment failed.

Below, you will find the error message I get:
![serverless-localstack-deployment-error](https://github.com/localstack/serverless-localstack/assets/32243459/35e9568b-af8e-4596-9590-ed15359ffa82)

I have aslo created [this](https://github.com/MarioSimou/serverless-localstack-deployment-issue) repository.

**Steps to reproduce:**
- Install node dependencies (`pnpm i`).
- Run localstack container. I am using v2.2 (`docker compose up -d localstack`).
- Deploy lambda function in localstack (`pnpm deploy:dev`). You should get the error message that I shared above.

**Comment by whummer** [comment]
Hi @MarioSimou , thanks for reporting. Can you please enable `DEBUG=1` in the LocalStack container environment, and then share the detailed debug logs here? This would be very helpful for us to reproduce and resolve this issue. Thanks for your help!

**Comment by MarioSimou** [comment]
Okay, I found the issue. I am not sure if its written anywhere in the documentation, but the localstack container needs to have the docker volume (`/var/run/docker.sock:/var/run/docker.sock`) attached to it. If not, cloudformation fails with an error similar to the one I shared above.

**Comment by steffyP** [comment]
Hi @MarioSimou,

great to hear that identified the problem! So we could close the ticket, or do you still have any issues?

We do have a documentation, respectively an example of the `docker-compose.yml` in our [docs here](https://docs.localstack.cloud/getting-started/installation/#starting-localstack-with-docker-compose).
It also states that the mount is required for lambda to work:

> Mounting the Docker socket /var/run/docker.sock as a volume is required for the Lambda service. Check out the [Lambda providers](https://docs.localstack.cloud/user-guide/aws/lambda/) documentation for more information.

Would you still expect additional information in our docs?

**Comment by MarioSimou** [comment]
Feel free to close it then. Thanks
