### ISSUE TITLE
Use awslocal from my host to localstack and use it into localstack container

### ISSUE THREAD

**Issue by Laurent45** [localstack/serverless-localstack#250]
Hello everyone.
I'm a little bit confused. I deployed an apiGateway with serverless-localstack and everything is done successfully.
When I check my APG with this command
``` bash
awslocal apigateway get-rest-apis
```
I have two different results according to my place.
When I run this command in my host, I have this result:
```json
{
    "items": []
}
```
And when I run this in the localstack container, I have this:
```json
{
    "items": [
        {
            "id": "hlbyuah2x3",
            "name": "OcBridgeApi",
            "createdDate": 1711038902.0,
            "apiKeySource": "HEADER",
            "endpointConfiguration": {
                "types": [
                    "EDGE"
                ]
            },
            "tags": {
                "aws:cloudformation:logical-id": "OcBridgeApi",
                "aws:cloudformation:stack-name": "users-dev",
                "aws:cloudformation:stack-id": "arn:aws:cloudformation:us-east-1:000000000000:stack/users-dev/b5c34ab6"
            },
            "disableExecuteApiEndpoint": false
        }
    ]
}
```
Can somebody please explain it to me, please?

**Comment by steffyP** [comment]
Hi @Laurent45,

it sounds like you maybe have a different default region set on your local machine vs in the container. 
Your stack-id in the container contains `us-east-1` so my guess that this is the region you deployed it to?

Try running the command locally with the region set, e.g. `awslocal apigateway get-rest-apis --region us-east-1`
Let us know if this works!

**Comment by Laurent45** [comment]
Hi @steffyP,
Thank you very much. Indeed the AWS region was the problem.
☺️
