### ISSUE TITLE
Getting invalid credentials

### ISSUE THREAD

**Issue by jgespinosa10** [localstack/serverless-localstack#260]
I'm encountering an error when trying to setup **serverless** and **localstack** in my local machine. 

```
$ serverless deploy

Deploying "serverless-localstack" to stage "local" (us-east-1)
Using serverless-localstack
Using serverless-localstack
serverless-localstack: Reconfigured endpoints
serverless-localstack: Reconfigured endpoints


✖ AWS credentials appear to be invalid. Run "serverless" to set up AWS credentials, or learn more in our docs: http://slss.io/aws-creds-setup. Original error from AWS: "The security token included in the request is invalid."
```

Here is the minimum amount of code to reproduce the error.
https://github.com/jgespinosa10/serverless-localstack

I'm using:
- localstack 3.5.0
- serverless 4.1.16
- node 20.12.2
- npm 10.5.0

Running on a MacBook Pro Intel Core i7 with macOs Sonoma v14.5

**Comment by MarcelStranak** [comment]
Hello @jgespinosa10,

After reviewing the sample, I suggest using only the supported versions of Lambda runtimes as listed in the [AWS documentation](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html). 

Additionally, to deploy the sample in LocalStack, please remove the following lines from your [serverless.yml file](https://github.com/jgespinosa10/serverless-localstack/blob/main/serverless.yml):
```yaml
org: jgespinosa10
app: serverless-localstack
```

Please follow the steps from our documentation page for [serverless-framework](https://docs.localstack.cloud/user-guide/integrations/serverless-framework/).

**Comment by dfloresgonz** [comment]
removed `org` and the error persists
