### ISSUE TITLE
How do you access API Gateway endpoints?

### ISSUE THREAD

**Issue by XaeroDegreaz** [localstack/serverless-localstack#28]
I've successfully deployed my API to Localstack, however there doesn't seem to be any obvious way of interacting with it.

The Serverless output of course points to URLs that don't exist in AWS, so I've tried variations of that ID paired with the deployment stage, as well as tried to hit endpoints found in http://localhost:4567/restapis using their IDs, and other combinations.

**Comment by whummer** [comment]
Thanks for reporting @XaeroDegreaz . The endpoint pattern is as follows:
```
http://localhost:4567/restapis/<rest_api_id>/dev/_user_request_/<method_path>
```
For example:
```
http://localhost:4567/restapis/1234-5678/dev/_user_request_/myapp
```
Good point - This still needs to be fixed in the Serverless output.

**Comment by XaeroDegreaz** [comment]
Thanks for the response. Is there any chance of having a more friendly URL scheme? Having to look up API IDs for all of the functions seems like a serious pain point for speed of testing.

It would be nice if it was simply something like

`http://localhost:4567/<stage>/<method_path>`

like how it is when testing against the real API Gateway service.

**Comment by CoreyCole** [comment]
@XaeroDegreaz once it is properly included in the serverless output, you can get access to it by parsing the `serverless info --stage local`:

```typescript
import * as shell from 'shelljs';

/**
 * Needs to be run inside a serverless directory (where a `serverless.yml` file is located)
 * @param stage dev | prod | ci-hash
 */
export const getServerlessInfo = (stage: string): string =>
    shell.exec(`serverless info --stage ${stage}`, { silent: true }).toString();

export const getLambdaUrls = (serverlessInfo: string): { [key: string]: string } => {
    const urls: { [key: string]: string } = {
        '/pathName1': null,
        '/pathName2': null,
        '/pathName3': null
    };
    
    getLinesWith('POST', serverlessInfo).forEach(urlLine => {
        const url = urlLine.substring(urlLine.indexOf('http'));
        const key = url.substring(url.lastIndexOf('/'));
        urls[key] = url;
    });

    return urls;
};

const getLinesWith = (lookingFor: string, input: string): string[] => {
    const lines = [];
    input.split('\n').forEach(line => {
        if (line.indexOf(lookingFor) >= 0) lines.push(line)
    });
    return lines;
}
```

**Comment by whummer** [comment]
This should be fixed in version `0.4.18` - the correct endpoints are now printed on `sls deploy`:
```
...
Service Information
service: test
stage: local
region: eu-central-1
stack: test-local
resources: 13
endpoints:
  POST - http://localhost:4567/restapis/txwn2s2eog/local/_user_request_/v1/request
functions:
  http_request: test-local-http_request
```
Closing this issue - please re-open if the problem persists. Thanks

**Comment by OnePunMan** [comment]
Hi, I am still encountering this on version 0.12.3 when I deploy on localstack Lambda. upon deploying using sls, I get this:
```
Service Information
service: my-service
stage: local
region: us-east-1
stack: my-service-local
resources: 11
api keys:
  None
endpoints:
  http://localhost:4566/restapis/0i514w1of2/local/_user_request_
functions:
  hello: my-service-local-hello
layers:
  None
```

I had to invoke the endpoint the old fashion way by following https://github.com/localstack/serverless-localstack/issues/28#issuecomment-500199803 (i.e. `http://localhost:4566/restapis/0i514w1of2/local/_user_request_/hello`). You can find the source code I used to reproduce the issue [here](https://github.com/OnePunMan/serverless-localstack-templates/tree/master/templates/python-lambda). It is a very simple template handler.

**Comment by morlombakop** [comment]
> ```ts
> serverlessInfo
> ```

@CoreyCole  how to use this?  I have been struggling to write api test.
