### ISSUE TITLE
Intermittent Error on Deployment "The specified bucket is not valid."

### ISSUE THREAD

**Issue by kevinswarner** [localstack/serverless-localstack#30]
I am getting an intermittent error when attempting to deploy to localstack using serverless.

First, I start localstack directly...

```
$ LAMBDA_EXECUTOR=docker SERVICES=lambda,cloudformation,s3,sts localstack start
Starting local dev environment. CTRL-C to quit.
Starting mock CloudWatch Logs (http port 4586)...
Starting mock CloudFormation (http port 4581)...
Starting mock S3 (http port 4572)...
Starting mock STS (http port 4592)...
Starting mock Lambda service (http port 4574)...
 * Serving Flask app "lambda_api" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Ready.
```

Then, very often, I get the following error when attempting to deploy...

```
kevinwarner ~/Documents/Projects/logicbox/localstack-test $ SLS_DEBUG=* AWS_PROFILE=wcf sls deploy -s local
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command deploy
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Using serverless-localstack
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Skip plugin function Package.packageService (lambda.mountCode flag is enabled)
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Skip plugin function AwsDeploy.extendedValidate (lambda.mountCode flag is enabled)
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 400 0.03s 0 retries] describeStacks({ StackName: 'localstack-test-local' })
Serverless: Creating Stack...
Serverless: [AWS cloudformation 400 0.119s 0 retries] createStack({ StackName: 'localstack-test-local',
  OnFailure: 'DELETE',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateBody: '{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket","Properties":{"BucketEncryption":{"ServerSideEncryptionConfiguration":[{"ServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}}}},"Outputs":{"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ] })

  Serverless Error ---------------------------------------

  The specified bucket is not valid.

  Stack Trace --------------------------------------------

ServerlessError: The specified bucket is not valid.
    at promise.catch.err (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:302:11)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           8.10.0
     Serverless Version:     1.44.1
```

Then, if I simply run the above depoy command again, often, but not always, the deploy works...

    $ SLS_DEBUG=* AWS_PROFILE=wcf sls deploy -s local
    Serverless: Load command config
    Serverless: Load command config:credentials
    Serverless: Load command create
    Serverless: Load command install
    Serverless: Load command package
    Serverless: Load command deploy
    Serverless: Load command deploy:function
    Serverless: Load command deploy:list
    Serverless: Load command deploy:list:functions
    Serverless: Load command invoke
    Serverless: Load command invoke:local
    Serverless: Load command info
    Serverless: Load command logs
    Serverless: Load command metrics
    Serverless: Load command print
    Serverless: Load command remove
    Serverless: Load command rollback
    Serverless: Load command rollback:function
    Serverless: Load command slstats
    Serverless: Load command plugin
    Serverless: Load command plugin
    Serverless: Load command plugin:install
    Serverless: Load command plugin
    Serverless: Load command plugin:uninstall
    Serverless: Load command plugin
    Serverless: Load command plugin:list
    Serverless: Load command plugin
    Serverless: Load command plugin:search
    Serverless: Load command config
    Serverless: Load command config:credentials
    Serverless: Load command rollback
    Serverless: Load command rollback:function
    Serverless: Load command deploy
    Serverless: Invoke deploy
    Serverless: Invoke package
    Serverless: Invoke aws:common:validate
    Serverless: Using serverless-localstack
    Serverless: Invoke aws:common:cleanupTempDir
    Serverless: Skip plugin function Package.packageService (lambda.mountCode flag is enabled)
    Serverless: Invoke aws:package:finalize
    Serverless: Invoke aws:common:moveArtifactsToPackage
    Serverless: Invoke aws:common:validate
    Serverless: Skip plugin function AwsDeploy.extendedValidate (lambda.mountCode flag is enabled)
    Serverless: Invoke aws:deploy:deploy
    Serverless: [AWS cloudformation 400 0.027s 0 retries] describeStacks({ StackName: 'localstack-test-local' })
    Serverless: Creating Stack...
    Serverless: [AWS cloudformation 200 0.054s 0 retries] createStack({ StackName: 'localstack-test-local',
      OnFailure: 'DELETE',
      Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
      Parameters: [ [length]: 0 ],
      TemplateBody: '{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket","Properties":{"BucketEncryption":{"ServerSideEncryptionConfiguration":[{"ServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}}}},"Outputs":{"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}',
      Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ] })
    Serverless: Checking Stack create progress...
    Serverless: [AWS cloudformation 200 0.017s 0 retries] describeStackEvents({ StackName: 'arn:aws:cloudformation:us-east-1:123456789:stack/localstack-test-local/5b67cb9f-5c6c-4730-a444-00baa75485ac' })
    ..
    Serverless: Stack create finished...
    Serverless: [AWS cloudformation 200 0.012s 0 retries] describeStackResource({ StackName: 'localstack-test-local',
      LogicalResourceId: 'ServerlessDeploymentBucket' })
    Serverless: [AWS s3 200 0.021s 0 retries] listObjectsV2({ Bucket: 'localstack-test-local-ServerlessDeploymentBucket-038864325861',
      Prefix: 'serverless/localstack-test/local' })
    Serverless: [AWS sts 200 0.018s 0 retries] getCallerIdentity({})
    Serverless: Uploading CloudFormation file to S3...
    Serverless: [AWS s3 200 0.012s 0 retries] putObject({ Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... >,
      Bucket: 'localstack-test-local-ServerlessDeploymentBucket-038864325861',
      Key: 'serverless/localstack-test/local/1559653335515-2019-06-04T13:02:15.515Z/compiled-cloudformation-template.json',
      ContentType: 'application/json',
      Metadata: { filesha256: 'YBpmXB/1aNso159t/k2HtYkUpYlTeKsLmNpnwJlAAX0=' } })
    Serverless: Skip plugin function AwsDeploy.uploadFunctionsAndLayers (lambda.mountCode flag is enabled)
    Serverless: Validating template...
    Serverless: Skipping template validation: Unsupported in Localstack
    Serverless: Updating Stack...
    Serverless: [AWS cloudformation 200 0.222s 0 retries] updateStack({ StackName: 'localstack-test-local',
      Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
      Parameters: [ [length]: 0 ],
      TemplateURL: 'https://s3.amazonaws.com/localstack-test-local-ServerlessDeploymentBucket-038864325861/serverless/localstack-test/local/1559653335515-2019-06-04T13:02:15.515Z/compiled-cloudformation-template.json',
      Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ] })
    Serverless: Checking Stack update progress...
    Serverless: [AWS cloudformation 200 0.016s 0 retries] describeStackEvents({ StackName: 'arn:aws:cloudformation:us-east-1:123456789:stack/localstack-test-local/5b67cb9f-5c6c-4730-a444-00baa75485ac' })
    ..
    Serverless: Stack update finished...
    Serverless: Invoke aws:info
    Serverless: [AWS cloudformation 200 0.021s 0 retries] describeStacks({ StackName: 'localstack-test-local' })
    Serverless: [AWS cloudformation 200 0.017s 0 retries] listStackResources({ StackName: 'localstack-test-local' })
    Service Information
    service: localstack-test
    stage: local
    region: us-east-1
    stack: localstack-test-local
    resources: 5
    api keys:
      None
    endpoints:
      None
    functions:
      hello: localstack-test-local-hello
    layers:
      None
    Serverless: Invoke aws:deploy:finalize
    Serverless: [AWS s3 200 0.01s 0 retries] listObjectsV2({ Bucket: 'localstack-test-local-ServerlessDeploymentBucket-038864325861',
      Prefix: 'serverless/localstack-test/local' })
    Serverless Enterprise: Run `serverless login` and deploy again to explore, monitor, secure your serverless project for free.Sometimes, the first attempt works, but sometimes it does not. Sometimes, it takes several deploy attempts to get it to work.

I really want to get this set up in my CI process, so this uncertainty is going to cause issues. Is there anything you see that is / could be causing the intermittent issue?

Note: I also get the same intermittent problem when starting localstack with all services.

Thanks!

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-45) by [Unito](https://www.unito.io/learn-more)

**Comment by kevinswarner** [comment]
Just a quick comment... I am waiting until the "localstack start" command responds with "ready" before attempting to deploy. One thought is that localstack is really not ready, even though it says it is.

**Comment by kevinswarner** [comment]
Another thought... I think this might have to do with the length of the deployment bucket name. When I deploy with serverless to AWS, the deployment bucket name gets truncated at 63 characters. I am not sure if serverless does this or AWS does this.

Through trial and error, I have determined that when I shorten my "service" name, it finally deploys without the error above.

Does the serverless localstack plugin take over the naming of the deployment bucket from serverless? If so, is it truncating the name to 63 characters? Just a thought.

Thanks.

**Comment by mikylebaksh** [comment]
Same, reduced my service name down to 5 characters and was able to deploy to localstack successfully

**Comment by benjaminlucchesi** [comment]
> Same, reduced my service name down to 5 characters and was able to deploy to localstack successfully

why the heck does this work???

**Comment by whummer** [comment]
Thanks for reporting @kevinswarner @mikylebaksh 

> Does the serverless localstack plugin take over the naming of the deployment bucket from serverless? If so, is it truncating the name to 63 characters?

Good catch about the maximum bucket name. The localstack serverless plugin itself should not be modifying the bucket name, though.

Can you post the relevant parts of your serverless.yml. In general, to my knowledge Serverless assumes that the deployment bucket already exists (also against real AWS), unless you use a plugin like `serverless-deployment-bucket`. 

There's also a way to customize the deployment bucket name in Serverless, for example:
```
...
provider:
  deploymentBucket:
    name: ${self:service}-${opt:stage}-deployment-bucket
...
```
Does that work?

**Comment by JakeChampion** [comment]
> Can you post the relevant parts of your serverless.yml. In general, to my knowledge Serverless assumes that the deployment bucket already exists (also against real AWS), unless you use a plugin like `serverless-deployment-bucket`.

That's not the case, if you don't provide your own bucket, Serverless will create a bucket which uses default AES256 encryption. This is mentioned in the [second bullet point under how it works](https://serverless.com/framework/docs/providers/aws/guide/deploying#how-it-works) and the [sixth bullet point under tips](https://serverless.com/framework/docs/providers/aws/guide/deploying#tips).

**Comment by pmyjavec** [comment]
I also hit this, for me it seems to have something to do with the bucket length.

**Comment by simonfrey** [comment]
Same problem here. Using a short bucket name does not help in my case.

```
service: bifrost-lambda
app: bifrostlambda
org: simonfrey
plugins:
  - serverless-localstack
  - serverless-deployment-bucket
custom:
  localstack:
    stages:
      - dev
    host: http://localhost
provider:
  name: aws
  runtime: nodejs12.x
  deploymentBucket:
    name: myb
    serverSideEncryption: AES256
  environment:
    variable1: value1
functions:
      login:
    handler: auth/api/customer/handler.login
    events:
      - http:
          path: auth/customers/login
          method: get
  checkLogin:
    handler: auth/api/customer/handler.checkLogin
    events:
      - http:
          path: auth/customers/checkLogin
          method: get
```

Results in:
```
sls deploy --stage dev --region us-east-1
Serverless: Using serverless-localstack
Serverless: Warning: Unable to find plugin named: TypeScriptPlugin
Serverless: Using deployment bucket 'myb'
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Safeguards Processing...
Serverless: Safeguards Results:

   Summary --------------------------------------------------

   passed - no-unsafe-wildcard-iam-permissions
   passed - allowed-runtimes
   passed - no-secret-env-vars
   warned - require-cfn-role
   passed - allowed-regions
   passed - framework-version
   passed - allowed-stages

   Details --------------------------------------------------

   1) Warned - no cfnRole set
      details: http://slss.io/sg-require-cfn-role
      Require the cfnRole option, which specifies a particular role for CloudFormation to assume while deploying.


Serverless: Safeguards Summary: 6 passed, 1 warnings, 0 errors
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service bifrost-lambda.zip file to S3 (4.16 MB)...
Serverless: Uploading custom CloudFormation resources...
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Updating Stack...
Serverless: Publishing service to the Serverless Dashboard...
Serverless: Successfully published your service to the Serverless Dashboard: https://dashboard.serverless.com/tenants/simonfrey/applications/bifrostlambda/services/bifrost-lambda/stage/dev/region/us-east-1
 
  Serverless Error ---------------------------------------
 
  The specified bucket does not exist
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              13.9.0
     Framework Version:         1.66.0
     Plugin Version:            3.5.0
     SDK Version:               2.3.0
     Components Version:        2.22.3
```

**Comment by sirjoe** [comment]
@simonfrey Have you managed to resolve your issue? I just run into the same problem.

**Comment by king-sam-perez** [comment]
I've run into the same issue as well. I'm just trying to test out the software by deploying some infrastructure locally and I'm getting the following:

``` Serverless Error ---------------------------------------
 
  The specified bucket is not valid.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.19.0
     Framework Version:         1.67.0
     Plugin Version:            3.6.2
     SDK Version:               2.3.0
     Components Version:        2.25.0```

and localstack says:

```
localstack_main | 2020-04-10T01:55:53:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "ServerlessDeploymentBucket": 400 Bad Request: <?xml version="1.0" encoding="UTF-8"?>
localstack_main | <Error>
localstack_main |     <Code>InvalidBucketName</Code>
localstack_main |     <Message>The specified bucket is not valid.</Message>
localstack_main |     
localstack_main |     <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
localstack_main | </Error> Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 183, in parse_and_create_resource
localstack_main |     return _parse_and_create_resource(
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 251, in _parse_and_create_resource
localstack_main |     raise moto_create_error
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 236, in _parse_and_create_resource
localstack_main |     resource = parse_and_create_resource_orig(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 345, in parse_and_create_resource
localstack_main |     resource = resource_class.create_from_cloudformation_json(
localstack_main |   File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 85, in Bucket_create_from_cloudformation_json
localstack_main |     result = create_from_cloudformation_json_orig(resource_name, cloudformation_json, region_name)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/models.py", line 1096, in create_from_cloudformation_json
localstack_main |     bucket = s3_backend.create_bucket(resource_name, region_name)
localstack_main |   File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 97, in create_bucket
localstack_main |     return create_bucket_orig(bucket_name, region_name, *args, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/models.py", line 1189, in create_bucket
localstack_main |     raise InvalidBucketName()
localstack_main | moto.s3.exceptions.InvalidBucketName: 400 Bad Request: <?xml version="1.0" encoding="UTF-8"?>
localstack_main | <Error>
localstack_main |     <Code>InvalidBucketName</Code>
localstack_main |     <Message>The specified bucket is not valid.</Message>
localstack_main |     
localstack_main |     <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
localstack_main | </Error>
```

I've literally just cloned localstack and have run `docker-compose up` as of commit `53690f2cdb96c4ea0a69bfb83ede39f3043c4a95`. Since apparently this was also an issue a few days ago, maybe I should using an official release. I'll report back if I figure anything out.

**Comment by pranjitk** [comment]
Same issue

**Comment by oromero-rv** [comment]
Has anyone figured out a fix for this? I just installed everything fresh and I'm running localstack in a Docker container with the docker-compose.yml file with no luck. I get this same error.

**Comment by jameswoodley** [comment]
Anyone got any more on this? I've got a bucket name of `widget-framework-db-local-deploy` I see it gets created in LocalStack, but serverless is still saying bucket name is invalid?

**Comment by nickygb** [comment]
I have solved this issue using conditional service name based on local deployment:

```yaml
service: ${self:custom.serviceName.${self:custom.currentStage}, self:custom.serviceName.other}
provider:
  stage: ${opt:stage, 'local'}
custom:
  currentStage: ${self:provider.stage}
  serviceName:
    local: <SHORT_SERVICE_NAME>
    other: <YOUR_ORIGINAL_SERVICE_NAME>



```

**Comment by dcabib** [comment]
> ```yaml
>   serviceName:
>     local: <SHORT_SERVICE_NAME>
>     other: <YOUR_ORIGINAL_SERVICE_NAME>
> ```

I've used your recommendation but I still having the issue:

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    endpointFile: resources/localstack/localstack_endpoints.json
    lambda:
      mountCode: True
  serviceName:
    local: test
    other: ${self:custom.config.appname}

**Comment by dcabib** [comment]
> I've run into the same issue as well. I'm just trying to test out the software by deploying some infrastructure locally and I'm getting the following:
> 
> ```
> Serverless Error ---------------------------------------
>  
>   The specified bucket is not valid.
>  
>   Get Support --------------------------------------------
>      Docs:          docs.serverless.com
>      Bugs:          github.com/serverless/serverless/issues
>      Issues:        forum.serverless.com
>  
>   Your Environment Information ---------------------------
>      Operating System:          darwin
>      Node Version:              10.19.0
>      Framework Version:         1.67.0
>      Plugin Version:            3.6.2
>      SDK Version:               2.3.0
>      Components Version:        2.25.0
> ```
> 
> and localstack says:
> 
> ```
> localstack_main | 2020-04-10T01:55:53:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "ServerlessDeploymentBucket": 400 Bad Request: <?xml version="1.0" encoding="UTF-8"?>
> localstack_main | <Error>
> localstack_main |     <Code>InvalidBucketName</Code>
> localstack_main |     <Message>The specified bucket is not valid.</Message>
> localstack_main |     
> localstack_main |     <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
> localstack_main | </Error> Traceback (most recent call last):
> localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 183, in parse_and_create_resource
> localstack_main |     return _parse_and_create_resource(
> localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 251, in _parse_and_create_resource
> localstack_main |     raise moto_create_error
> localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 236, in _parse_and_create_resource
> localstack_main |     resource = parse_and_create_resource_orig(
> localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 345, in parse_and_create_resource
> localstack_main |     resource = resource_class.create_from_cloudformation_json(
> localstack_main |   File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 85, in Bucket_create_from_cloudformation_json
> localstack_main |     result = create_from_cloudformation_json_orig(resource_name, cloudformation_json, region_name)
> localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/models.py", line 1096, in create_from_cloudformation_json
> localstack_main |     bucket = s3_backend.create_bucket(resource_name, region_name)
> localstack_main |   File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 97, in create_bucket
> localstack_main |     return create_bucket_orig(bucket_name, region_name, *args, **kwargs)
> localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/models.py", line 1189, in create_bucket
> localstack_main |     raise InvalidBucketName()
> localstack_main | moto.s3.exceptions.InvalidBucketName: 400 Bad Request: <?xml version="1.0" encoding="UTF-8"?>
> localstack_main | <Error>
> localstack_main |     <Code>InvalidBucketName</Code>
> localstack_main |     <Message>The specified bucket is not valid.</Message>
> localstack_main |     
> localstack_main |     <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
> localstack_main | </Error>
> ```
> 
> I've literally just cloned localstack and have run `docker-compose up` as of commit `53690f2cdb96c4ea0a69bfb83ede39f3043c4a95`. Since apparently this was also an issue a few days ago, maybe I should using an official release. I'll report back if I figure anything out.

Did you have any luck?

**Comment by nickygb** [comment]
> > ```yaml
> >   serviceName:
> >     local: <SHORT_SERVICE_NAME>
> >     other: <YOUR_ORIGINAL_SERVICE_NAME>
> > ```
> 
> I've used your recommendation but I still having the issue:
> 
> custom:
> localstack:
> stages:
> - local
> host: http://localhost
> endpointFile: resources/localstack/localstack_endpoints.json
> lambda:
> mountCode: True
> serviceName:
> local: test
> other: ${self:custom.config.appname}

@dcabib 

Did you set the service using the custom.serviceName variable? and did you run serverless in **local** stage ```sls deploy -s local```

```yaml
service: ${self:custom.serviceName.${self:custom.currentStage}, self:custom.serviceName.other}
```

**Comment by chriszirkel** [comment]
Changing the service name to a shorter name resolved the deployment issue for me.

**Comment by whummer** [comment]
Thanks for confirming the fix @chriszirkel . Closing this issue as resolved for now - please let us know if the problem persists @dcabib  @oromero-rv @jameswoodley . Thanks
