### ISSUE TITLE
Remove of very simple serverless stack fails

### ISSUE THREAD

**Issue by pellcorp** [localstack/serverless-localstack#35]
I created a sample project:
https://github.com/pellcorp/serverless-localstack-test

I docker-compose up in one window
Then in a separate window I do the sls deploy, which does work
But sls remove fails.

[deploy.log](https://github.com/localstack/serverless-localstack/files/3504399/deploy.log)
[docker.log](https://github.com/localstack/serverless-localstack/files/3504400/docker.log)
[remove.log](https://github.com/localstack/serverless-localstack/files/3504397/remove.log)

**Comment by winly19** [comment]
> I created a sample project:
> https://github.com/pellcorp/serverless-localstack-test
> 
> I docker-compose up in one window
> Then in a separate window I do the sls deploy, which does work
> But sls remove fails.
> 
> [deploy.log](https://github.com/localstack/serverless-localstack/files/3504399/deploy.log)
> [docker.log](https://github.com/localstack/serverless-localstack/files/3504400/docker.log)
> [remove.log](https://github.com/localstack/serverless-localstack/files/3504397/remove.log)

**Comment by whummer** [comment]
Thanks for reporting @pellcorp . This should be fixed in https://github.com/localstack/localstack/pull/1911 - can you please give it a try with the latest version of this library, and of the `localstack/localstack` Docker image? Thanks
