### ISSUE TITLE
Usage with Webpack

### ISSUE THREAD

**Issue by chrisandrews7** [localstack/serverless-localstack#42]
When using [localstack.lambda.mountCode](https://github.com/localstack/serverless-localstack#mounting-lambda-code-for-better-performance), the handler file is used when the running the lambda inside the localstack container:

```bash
docker run -i  -v "/xx/folder":/var/task -e ...  --rm "lambci/lambda:nodejs8.10" "./src/functions/index.handler"
```

As the `./src/functions/index.handler` is the un-transpiled version, as it hasnt gone through [webpack](https://github.com/serverless-heaven/serverless-webpack) yet, it errors.

How would you recommend using [localstack.lambda.mountCode](https://github.com/localstack/serverless-localstack#mounting-lambda-code-for-better-performance) with [serverless-webpack](https://github.com/serverless-heaven/serverless-webpack)?

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-46) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @chrisandrews7 . Can you please provide a small, self-contained working example (code+config) to reproduce this issue? Happy to take a look at it. Thanks

**Comment by beau6183** [comment]
@whummer Here's an example: https://github.com/beau6183/sls-localstack-lambda-typescript-webpack-mount

**Comment by hansffu** [comment]
We got around this by patching the build dir 
```diff
diff --git a/node_modules/serverless-localstack/src/index.js b/node_modules/serverless-localstack/src/index.js
index 55c7811..212c81c 100644
--- a/node_modules/serverless-localstack/src/index.js
+++ b/node_modules/serverless-localstack/src/index.js
@@ -9,7 +9,7 @@ const DEFAULT_STAGE = 'dev';
 // Strings or other values considered to represent "true"
 const TRUE_VALUES = ['1', 'true', true];
 // Build directory of serverless-plugin-typescript plugin
-const TYPESCRIPT_PLUGIN_BUILD_DIR = '.build';
+const TYPESCRIPT_PLUGIN_BUILD_DIR = '.webpack/service';
 // Default edge port to use with host
 const DEFAULT_EDGE_PORT = '4566'
 
@@ -367,7 +367,7 @@ class LocalstackPlugin {
    * used, and (2) lambda.mountCode is enabled.
    */
   patchTypeScriptPluginMountedCodeLocation() {
-    if (!this.shouldMountCode() || !this.findPlugin('TypeScriptPlugin')) {
+    if (!this.isActive()) {
       return;
     }
     const template = this.serverless.service.provider.compiledCloudFormationTemplate || {};
```
And then telling `serverless-webpack` to keep it
```yaml
custom:
  webpack:
    keepOutputDirectory: true
```

**Comment by beau6183** [comment]
Awesome, @hansffu, gonna give this a try. If that works, maybe issue a PR for it?
