### ISSUE TITLE
Fn::GetAtt with S3

### ISSUE THREAD

**Issue by askharryclarke** [localstack/serverless-localstack#44]
I have a simple S3 bucket 'MyBucket' declared alongside an IAM Role 'MyBucketRole', if I attempt to access the bucket's ARN via:
                                           { "Fn::GetAtt": ["MyBucket", "Arn"] }
it will throw:
Template error: resource CommandArchive does not support attribute type Arn in Fn::GetAtt

However, if I attempt to access the ARN via:
               { "Fn::GetAtt": [{"Fn::GetAtt": ["MyBucket", "BucketName"]}, "Arn"] }
it works fine.

Under normal Serverless circumstance the first option works fine, am I being silly or is this a legitimate/known issue?

**Comment by askharryclarke** [comment]
UPDATE: It also appears that the working version only works if the resource is already deployed. If  attempting to launch both bucket and role attached to bucket at the same time, results in the following error:

ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "MyBucketRole": unhashable type: 'dict'

Serverless also throws a 500 error.

**Comment by kshahzada** [comment]
I'm getting this same issue when I deploy with sls deploy; as a temporary work around, if I docker-compose localstack and set `autostart: false` it deploys the bucket fine.

**Comment by kshahzada** [comment]
Found this in template_deployer.py (below), which looks correct. My guess is that when it's deployed with the serverless plugin, it must be giving it a different bucket-name temporarily or something. With some guidance, I'd be happy to find the fix.
```
       elif len(value) == 1 and 'Fn::GetAtt' in value:
            return resolve_ref(stack_name, value['Fn::GetAtt'][0],
                resources, attribute=value['Fn::GetAtt'][1])
```

**Comment by whummer** [comment]
Thanks for reporting @askharryclarke @kshahzada . Would you be able to provide a small, self-contained example that allows to reproduce this issue? That would be very appreciated, thanks.

**Comment by whummer** [comment]
@askharryclarke @kshahzada This appears to be fixed in the `latest` version of LocalStack.

Given this serverless.yml:
```
service: test123

resources:
  Resources:
    MyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: test1
    MyRole:
      Type: AWS::IAM::Role
      Properties:
        Name: role1
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: test
              Resource: { "Fn::GetAtt": ["MyBucket", "Arn"] }

plugins:
  - serverless-localstack
  - serverless-deployment-bucket

custom:
  localstack:
    stages:
      - local

provider:
  name: aws
```

Deploying the template works successfully:
```
$ sls deploy --stage local
...
Serverless: Stack update finished...
...
```
... and the resource is created successfully:
```
$ awslocal iam list-roles
...
                        "Resource": "arn:aws:s3:::test1"
...
```

Please provide more details to reproduce if this problem persists. Thanks
