### ISSUE TITLE
AWS config ignored

### ISSUE THREAD

**Issue by rjamesnw** [localstack/serverless-localstack#45]
The `cli_follow_urlparam` setting in the AWS config is ignored, causing my scripts that set SSM properties with HTTP values to fail.  It fails because the dumb default behavior is to attempt to read values from the HTTP endpoints, instead of just treating the HTTP endpoints as values.  I don't see any way to change that for localstack. Is there some other config file I should be setting?

(more on the setting here: https://github.com/aws/aws-cli/issues/3451)

**Comment by whummer** [comment]
Thanks for reporting @rjamesnw . Do you think you could provide a small self-contained example project to reproduce this issue? Thanks!

**Comment by rjamesnw** [comment]
Since everyone uses different IDEs it is better to explain the steps:

1. Try to create an SSM property:
    > aws. ssm put-parameter --name /test/propa --value "http://theres.nothinghere.com/abc" --type String --region us-east-1 --overwrite

There, simple enough? ;)  You don't need a project for that.  It doesn't work, because AWS, by default, treats URLs as value SOURCES, which is just stupid, and the only way to treat the URL as a STRING value is to set `cli_follow_urlparam=false` in the AWS config file.

Read more about it here: https://github.com/aws/aws-cli/issues/3451

**Comment by whummer** [comment]
I see, thanks for providing the example. This is indeed a weird/unexpected behavior from AWS side. 

This is actually an upstream issue in https://github.com/spulec/moto , which LocalStack use under the covers to provide SSM support. Would you mind creating an issue there? Once this issue is fixed in moto, we'll integrate it in an upcoming release of LocalStack. Thanks

**Comment by rjamesnw** [comment]
They are saying it is not an issue with Moto.

https://github.com/spulec/moto/issues/2498

Perhaps you can jump on the thread and give more insight.  I know nothing about how the underlying system works.
