### ISSUE TITLE
PathParameters should be None and not an empty Json object

### ISSUE THREAD

**Issue by Rahulnigam28** [localstack/serverless-localstack#48]
While calling serverless localstack, events["pathParameters"] in the event resource should default to None instead of an empty dict. 

In AWS , default value for event["pathParameters"] is None.

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-48) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @Rahulnigam28 - any chance you can provide a small, self-contained example (ideally a small project in a GIthub repo) to easily reproduce this issue? Thanks!
