### ISSUE TITLE
security token is invalid

### ISSUE THREAD

**Issue by gcampionpae** [localstack/serverless-localstack#62]
Hi there,

I'm trying to use your plugin with serverless 1.60.0 and I cannot seem to get past serverless checking the security token when deploying.  I get this error and can't figure out how to stop it from happening:

Serverless: Using serverless-localstack
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 403 0.29s 0 retries] describeStacks({ StackName: 'sls-sendgrid-local' })

  Serverless Error ---------------------------------------

  ServerlessError: The security token included in the request is invalid.
      at promise.catch.err (/sls_plugins/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:326:27)
      at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by whummer** [comment]
Thanks for reporting @gcampionpae . This error seems to indicate that the plugin is not activated properly, i.e., that Serverless is attempting to contact real AWS instead of the local APIs.

Can you please share the relevant parts of your `serverless.yml`, and the exact serverless command you're running. Thanks

**Comment by gcampionpae** [comment]
Hi @whummer thanks for the quick response!

here is the part for localstack
```
custom:
  stage: "${opt:stage, self:provider.stage}"
  account_id: ${file(environment.yml):${self:custom.stage}.AWS_ACCOUNT_ID}
  region: "${opt:region, self:provider.region}"
  lambda_arn_prefix: "arn:aws:lambda:${self:custom.region}:${self:custom.account_id}:function:${self:service}-${self:custom.stage}"
  prune:
    automatic: true
    number: 5
  pythonRequirements: # Override default noDeploy configuration because of https://github.com/UnitedIncome/serverless-python-requirements/issues/163
    pythonBin: ${self:provider.runtime}
    noDeploy:
      [
        'boto3',
        'botocore',
        'docutils',
        'jmespath',
        'python-dateutil',
        's3transfer',
        'six',
        'pip',
        #'setuptools'
      ]
    localstack:
      stages:
        - local
      host: http://192.168.5.241
      lambda:
        mountCode: False
```

and here is the command
```
sls deploy -s local --profile local
```
and here is my cred config

```
[local]
aws_access_key_id     = 1234
aws_secret_access_key = 5678
```

**Comment by whummer** [comment]
@gcampionpae just to confirm - is the `localstack` section of the yaml config a direct child of the `custom` node? From the indentation you posted, it looks like `localstack` is a child of the `pythonRequirements` node..?

Still, it's a bit weird that you're getting this error after seeing the `Using serverless-localstack` log output, but I'd like to confirm this first before we dig deeper. Thanks.

**Comment by gcampionpae** [comment]
Yeah that was the issue, I indented incorrectly :/
