### ISSUE TITLE
Endpoint URLs are replaced with localstack URLs when not deploying to localstack

### ISSUE THREAD

**Issue by jacsamell** [localstack/serverless-localstack#63]
When deploying to a real stage on AWS and not a localstack stage the logged endpoint urls are incorrectly replaced with localstack ones.

![image](https://user-images.githubusercontent.com/33119300/71267182-e7fa2c00-2341-11ea-9ea3-6ae105a54318.png)

I think the issue may be that the LocalStack plugin constructor adds the hook to replace the URLs which has no check for the stage when deploying:

![image](https://user-images.githubusercontent.com/33119300/71267445-75d61700-2342-11ea-96a5-6411e780aacf.png)

**Comment by whummer** [comment]
Thanks for reporting @jacsamell . This should be fixed in #66 - we'll publish a new npm release shortly.
