### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'stack_resources'

### ISSUE THREAD

**Issue by blbradley** [localstack/serverless-localstack#71]
I'm experiencing this while using this plugin with `serverless-plugin-split-stacks`.

Suggestions?

[A similar error](https://github.com/localstack/localstack/issues/1694) has been reported upstream.

**Comment by whummer** [comment]
Thanks for reporting @blbradley . Do you think you can provide a small, self-contained example to reproduce this issue? Thanks

**Comment by blbradley** [comment]
hey @whummer, yea can you go here to take a look?

spulec/moto#2708

**Comment by blbradley** [comment]
upstream issue localstack/localstack#1989

**Comment by whummer** [comment]
Upstream issue in moto has been fixed, the change is included in LocalStack latest. Can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
