### ISSUE TITLE
mountCode throwing NoSuchBucket errors

### ISSUE THREAD

**Issue by byroncoetsee** [localstack/serverless-localstack#84]
Enabling `mountCode` within `lambda` as per the examples, throws the error `Error response for CloudFormation action "UpdateStack" (400) POST /: b'Error occurred while GetObject. S3 Error Code: NoSuchBucket. S3 Error Message: The specified bucket does not exist'`

Some more useful info might be 
```
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/models.py", line 1199, in get_bucket

return self.buckets[bucket_name]

KeyError: '__local__'
```
If you'd like more errors or the entire log, let me know.

I do remember setting the s3 bucket name to `__local__` when creating a bucket using the CLI but not sure if that makes any difference - I'm new to AWS.

Disabling `mountCode` works perfectly, its just longer to deploy (locally of course).

```
     Python 3.8
     Operating System:        darwin
     Node Version:                12.9.0
     Framework Version:      1.67.0
     Plugin Version:               3.6.1
     SDK Version:                  2.3.0
     Components Version:   2.22.3
```

Any suggestions? Been at this for most of the day now and I'm done.
Thank you

**Comment by whummer** [comment]
Thanks for reporting @byroncoetsee . This should be fixed in https://github.com/localstack/localstack/pull/2220, can you please give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
