### ISSUE TITLE
Support for Go runtime in Lambda functions

### ISSUE THREAD

**Issue by RaeesBhatti** [localstack/serverless-localstack#94]
It would be nice to have support for Golang Lambda function in `serverless-localstack`!

**Comment by whummer** [comment]
Thanks for reporting @RaeesBhatti . Can you please provide a small, isolated example to help reproduce your issue? The `go1.x` runtime _should_ technically be supported in LocalStack - support has been added in this PR: https://github.com/localstack/localstack/pull/617 . Closing this issue, as this is technically not an issue related to `serverless-localstack`, but please feel free to re-open or create a new issue in the main LocalStack repo if you can provide more details an a full example with error details to reproduce. Thanks!
